// <auto-generated />
namespace ExplorersEarlyLearning.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Menu4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Menu4));
        
        string IMigrationMetadata.Id
        {
            get { return "201404151628399_Menu4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
