// <auto-generated />
namespace ExplorersEarlyLearning.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Menu1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Menu1));
        
        string IMigrationMetadata.Id
        {
            get { return "201404110743006_Menu1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
